### PR TITLE
Fix gradle  issue on macos

### PR DESCRIPTION
**Pull request by BoogieMonster1O1**
Now actually works on mac :p

### CODE REVIEW

**Comment by Chocohead** [comment]
I should have fixed this in Loom [here](https://github.com/Chocohead/Fabric-Loom/commit/fddfa4da5e50f9af2d70e2eb75b2abd6db7971d8#diff-f1d482bd2d6d4f819b7b014d0b82e86dffce9d53f0bc9c72c36ce88e5f6b3945R92-R102). It shouldn't need manually overriding at least.

**Comment by valoeghese** [comment]
Can you confirm whether this still needs to be merged, boogie?

**Comment by valoeghese** [comment]
This pull request has been automatically marked as stale because it has not had recent activity, and will be closed if no further activity occurs. If this pull request was overlooked, forgotten, or should remain open for any other reason, please reply here to call attention to it and remove the stale status. Thank you for your contributions.

**Comment by valoeghese** [comment]
This pull request has been automatically closed because it has not had recent activity. Please feel free to update or reopen it.

**Pull request closed without merging**
